---
name: Test Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test-container:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-test-container.yml@ba4afa056baf1ca2df3fa0f898404988bf6e7478 # v3.2.2
